name: Terraform - Provision EKS

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      TF_VAR_cluster_name: "eks-test-cluster"

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configure AWS credentials for the GitHub Actions role
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::713881830177:role/GitHubActionsECRPushRole
          aws-region: ${{ env.AWS_REGION }}

      # 3. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.7  # adjust version if needed

      # 4. Initialize Terraform with existing S3 + DynamoDB backend
      - name: Terraform Init
        working-directory: terraform/environments/test
        run: terraform init

      # 5. Terraform Plan
      - name: Terraform Plan
        working-directory: terraform/environments/test
        run: terraform plan -out=tfplan

      # 6. Terraform Apply
      - name: Terraform Apply
        working-directory: terraform/environments/test
        run: terraform apply -auto-approve tfplan